- name: Install base packages
  pkg: name={{ item }} state=installed
  with_items:
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - supervisor
    - nginx
  tags:
    - packages