---
- name: converge
  hosts: server
  become: true
  

  vars:
    postgresql_database:
      - name: "{{remote_users}}"
    postgresql_user:
      - naem: "{{password}}"  
  tasks:
   - name: postgresql96-server
     package:
        name: postgresql96-server
        state: present 
   - name: postgresql96-server
     service:
        name: postgresql96-server
        state: started
   #- name: Start postgresq automatically
   #    command: sysrc postgresql_enable=yes\   
   -name: Edit postgresql.conf
        command: echo configure postgresql
   - name: Init postgresql
        command: sudo service postgresql oneinitdb
   - name: Start postgresql
        command: sudo service postgresql onestart
# dump requires a target definition to which the database will be backed up
# present implies that the database should be created if necessary