---
- name: Create Jail  
  hosts: localhost
  become: yes

  gather_facts: no
  tasks:
  - name: Create Brand new Jail
    command: ezjail-admin create  gohan 'l01|127.0.0.1,em0|192.168.1.125' 
  - name: Start Jail
    command: service jail start gohan
