---
- name: Config  debugger: true
  hosts: servers
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: Create Brand new Jail
    command: ezjail-admin create  gohan 'l01|127.0.0.1,em0|192.168.1.125' 
  - name: Start Jail
    command: ezjail-admin start gohan