---
- name: Web01
  hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: (ansible officalfreebsd.com --sudo -m raw -a "yum install -y python2" && sudo pkg install py27-ansible)