---
- name: Web01
  hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: pkg install /usr/local/bin/python
      changed_when: False
    - setup: # aka gather_facts