---
- name: AnsibleConfiguration
  debugger: true
  hosts: servers
  become: yes
  gather_facts: yes
  vars:
   ansible_python_interpreter: "/usr/local/bin/python2.7"
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/local/bin/python2.7 || (pkg -y update && pkg install -y python2)
      changed_when: False
    - setup: # aka gather_facts
  tasks:
  - name: ensure pip
    command: python -m ensurepip
  - name: Install pathlib module
    command: pip install pathlib
  - name: Install SBCL
    command: pkg install -y sbcl
  - name: Insatll Git
    command: pkg install -y git
  - name: Create Scripts dir 
    file: path=/home/codejenkins/scripts state=directory
  - name: Go to the folder and execute clone
    command: chdir=/home/codejenkins/scripts git clone https://github.com/dr3amtech/AnsiblePlaybook.git 
  - name: Python Jail Install/creator
    command: python /home/codejenkins/scripts/AnsiblePlaybook/AnsiblePlaybook/Inventories/develop/common/script/dragoncreator.py
  - name: Python postgresql installer
    command: python /home/codejenkins/scripts/AnsiblePlaybook/AnsiblePlaybook/Inventories/develop/common/script/dragonchestcreator.py
  - name: Install Ngnix
    command: python /home/codejenkins/scripts/AnsiblePlaybook/AnsiblePlaybook/Inventories/develop/common/script/numbus.py
  - name: Install OpenCV
    command: pkg install -y opencv
  - name: Install OpenCL
    command: pkg install -y opencl
  - name: Install node 
    command: pkg install -y node 
  - name: Install neo4j 
    command: pkg install -y neo4j  
  - name: Install npm:
    command pkg install -y npm
  - name: Install node
    command: pkg install -y node
  - name: Installing Angular
    command: npm install -g @angular/cli
  - name: Install redis package 
    command: pkg install -y redis
