---
- name: Web01
  debugger: true
  hosts: servers
  become: yes
  gather_facts: False
  tasks:
  - name: return motd to registered var
    command: sudo pkg install python27
  - name: return motd to registered var
    command: sudo pkg install py27-ansible