---
- name: Web01
  debugger: true
  hosts: servers
  become: yes
  become_method: sudo
  gather_facts: False
  vars:
   ansible_python_interpreter: "/usr/local/bin/python2.7"
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/local/bin/python2.7 || (pkg -y update && pkg install -y python2)
      changed_when: False
    - setup: # aka gather_facts
  tasks:
  - name: Install SBCL
    command: pkg install sbcl
  - name: Install curl
    command: pkg install curl 
  - name: Download quicklisp
    command: curl -O https://beta.quicklisp.org/quicklisp.lisp
  - name: Load quicklisp
    command: sbcl --load quicklisp.lisp
  - name: Install quick lisp
    command: quicklisp-quickstart:install