---
- name: Web01
  hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (pkg -y update && pkg install -y python-minimal)
      changed_when: False
    - setup: # aka gather_facts
  roles:
    - base