---
- name: Web01
  hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install Ansible
      raw: sudo pkg install py27-ansible
      raw: ansible officalfreebsd.com --sudo -m raw -a "yum install -y python2"