---
- name: Web01
  debugger: true
  hosts: servers
  become: yes
  gather_facts: False
  - name: Install a list of packages
    yum:
      name:
        - py27-ansible
        - SBCL
        - curl
    state: present