---
- name: Web01
  debugger: true
  hosts: servers
  become: yes
  gather_facts: False
  vars:
   ansible_python_interpreter: "/usr/bin/local/python2.7"
  tasks:
  - name: return motd to registered var
    command: sudo pkg install py27-ansible