---
- name: Web01
  hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: (pkg install python27 && pkg install git)
    - name: Install ntp
      raw: (cd /usr/ports/lang/sbcl/ && make install clean)