---
- name: Web01
  debugger: true
  hosts: servers
  become: yes
  gather_facts: False
  tasks:
  - name: install python2
    raw: sudo apt-get -y install python-simplejson
  - name: return motd to registered var
    command: sudo pkg install py27-ansible