---
- name: Web01
  debugger: true
  hosts: servers
  become: yes
  gather_facts: False
  tasks:
  - name: install python2
    command: ansible officalfreebsd.com --sudo -m raw -a "yum install -y python2"
  - name: return motd to registered var
    command: sudo pkg install py27-ansible